Increment to version 1.1.0, add TypeScript typings.
mapbox/potpack pull request #7
Opened 2021-08-19 17:05 UTC by mbullington

Hello!

I incremented the package to v`1.1.0`, the only change being some TS typings I wrote for the package and I found more-generally useful.

2021-08-19 17:20 UTC, mourner requested changes
This looks good to me apart from the version change — I'm doing it as a part of `npm version` in a separate commit so let's leave that out.

2021-08-26 13:59 UTC, mourner approved these changes

2021-08-26 13:59 UTC, merged

2021-10-18 19:46 UTC, HarelM commented
I see that I don't need to send a PR with typings :-)
Any chance to release a version containing this please?

2021-10-22 08:28 UTC, mourner commented
> Any chance to release a version containing this please?

Yep, released as v1.0.2.